"""add desc in categories

Revision ID: 13441c65e201
Revises: ebef9702ecfa
Create Date: 2025-03-09 14:18:09.602505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13441c65e201'
down_revision = 'ebef9702ecfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
