"""empty message

Revision ID: 34fec91d446d
Revises: 898998b16151
Create Date: 2025-03-10 13:21:22.130086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34fec91d446d'
down_revision = '898998b16151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_invitations')
    op.drop_table('mfa_codes')
    op.drop_table('wallet_collaborators')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('alert_threshold')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_default')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('related_entity_type')
        batch_op.drop_column('action_url')
        batch_op.drop_column('related_entity_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_created_by_fkey', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('recurring_end_date')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('mfa_method')
        batch_op.drop_column('mfa_phone')
        batch_op.drop_column('notification_preferences')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('is_shared')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_preferences', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'{"push": false, "email": true, "budget_alerts": true, "security_alerts": true}\'::jsonb'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mfa_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mfa_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mfa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('transactions_created_by_fkey', 'users', ['created_by'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_entity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('related_entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('categories_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    op.create_table('wallet_collaborators',
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallet_collaborators_user_id_fkey'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='wallet_collaborators_wallet_id_fkey'),
    sa.PrimaryKeyConstraint('wallet_id', 'user_id', name='wallet_collaborators_pkey')
    )
    op.create_table('mfa_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mfa_codes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mfa_codes_pkey')
    )
    op.create_table('wallet_invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='wallet_invitations_sender_id_fkey'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='wallet_invitations_wallet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallet_invitations_pkey')
    )
    # ### end Alembic commands ###
